### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by irekg** [devballteam/promonitor#10]
I'm not sure how it should look like. DevBall logo?

**Comment by mbogatzki** [comment]
Use this one :)
[favicon.ico.zip](https://github.com/devballteam/promonitor/files/2585321/favicon.ico.zip)

**Comment by irekg** [comment]
Done https://github.com/devballteam/promonitor/commit/19a1cc0820ac5a060dc4d91b190a6a81399436ca
