### ISSUE TITLE
Add aggregated statistics for past period about average time for PR being opened, average size etc

### ISSUE THREAD

**Issue by lukasz-gawron** [devballteam/promonitor#6]
It would allow to track trends and make conclusions, plan improvements based on that.
Something like in insight tab.

**Comment by irekg** [comment]
It doesn't look like feature for this tool. You can simply achieve that using github api. Just call for all closed pull requests from chosen repository. Then in main PR data you will find creation time and close time. Store all of it in some table and calculate average time.

For size it's a little more complicated. If i'm correct you have to get all commits data for each PR. Inside commit data you can find informations about number of changes and files.

**Comment by lukasz-gawron** [comment]
Thanks for feedback, make sense.
