### ISSUE TITLE
Uncheck PR if the review was added before last commit

### ISSUE THREAD

**Issue by esuszek** [devballteam/promonitor#7]
Not a single line of code should go to develop without review. **Not. A. Single. Line.**

**Comment by mpietrowiak** [comment]
I agree, but is it possible on GitHub side?

Because I think we can unmark the approve on pr monitor side but then the approve would stay in github, so that would cause inconsistency

**Comment by irekg** [comment]
We can't do it in github but monitoring have it. Reviews older than last commit are hidden.
